### ISSUE TITLE
Navigating the browser left or right changes zoom level

### ISSUE THREAD

**Issue by martinaryee** [aryeelab/DNAlandscapeR#21]
When you move left or right (e.g. ">>") the zoom level changes on the plot.

**Comment by caleblareau** [comment]
I wasn't able to reproduce this error... The width was consistent for me after hitting all four buttons. 

One area where I could imagine that you ran into this problem was shifting toward the end of a chromosome. Say the chromosome ends at 900, you're at 500-800, and then shift right (">>"). Double arrows means 90% of the width, so you'd move 300 * .9 = 270 base pairs right, putting you at 770-1070. However, DNAlandscapeR does a check to see if you're at the end of the chromosome, which is the case here, so the browser would display 770-900 to avoid cases of being out of bounds. 

Does this description fit the issue you came across?

**Comment by martinaryee** [comment]
Yes - That is what happened. I had zoomed out to almost a whole chromosome view and this is why I ended up at the edge of the chr. Closing the issue - thanks.
